language: java
sudo: false
install: true

jdk:
  - oraclejdk8

script:
  # JaCoCo is used to have code coverage, "-Pcoverage" activates the maven profile in the pom.xml
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.host.url=https://next.sonarqube.com/sonarqube/

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
